# Site settings
title: Stop Macro Mataderos
email: stopmacromataderozafra@gmail.com
description: "Detengamos la construcción de los Macro Mataderos. Firma las peticiones y juntos podremos ponerle fin a esto."

# Build settings
markdown: kramdown
permalink: pretty